# this is general static configuration (in Git repo)
# - todo: you can override this configuration by adding a config.local.yml
# - config.local.yml (if it exists) will override config.yml

general:
  verbose: true

github:
  cmd:
    baseURl:  https://api.github.com/
  repos:
    typo3-documentation:
      ignore:
        - TYPO3CMS-Reference-FileAbstractionLayer
        - TYPO3CMS-Tutorial-CreatingExtensions
        - TYPO3CMS-Guide-Extbase
    typo3:
      ignore:
#        - .github
    friendsoftypo3:
      ignore:
#        - github
