# this is general static configuration (in Git repo)
# - config.local.yml (if it exists) will override config.yml

general:
  verbose: true

hosts:
  github.com:
    type: github
    api_url: "https://api.github.com/"
    ssh_url: "git@github.com:%s/%s.git"
    repos:
      friendsoftypo3:
      typo3:
      typo3-documentation:
        ignore:
          - TYPO3CMS-Reference-FileAbstractionLayer
          - TYPO3CMS-Tutorial-CreatingExtensions
          - TYPO3CMS-Guide-Extbase
      # typo3-console:
        # include:
          # - typo3-console

#  gitlab.com:
#    type: gitlab
#    api_url: "https://gitlab.com/api/v4/"
#    ssh_url: "git@gitlab.com:%s/%s.git"
#    repos:
#      coderscare:
#        include:
#          - gridelements
