# this is general static configuration (in Git repo)
# - config.local.yml (if it exists) will override config.yml

general:
  verbose: true

github:
  cmd:
    baseURl:  https://api.github.com/
  repos:
    friendsoftypo3:
    typo3:
    typo3-documentation:
      ignore:
        - TYPO3CMS-Reference-FileAbstractionLayer
        - TYPO3CMS-Tutorial-CreatingExtensions
        - TYPO3CMS-Guide-Extbase
    # typo3-console:
      # include:
        # - typo3-console
